[package]
name = "client-test"
version = "0.1.0"
edition = "2021"

[dependencies]

ethers = { version = "2.0", features = ["ws", "rustls"] }
tokio = { version = "1.0", features = ["full"] }
dotenv = "0.15"
eyre = "0.6"
serde_json = "1.0"

